"""add board_id to lists

Revision ID: ac71f4e22c43
Revises: aaa252b7c6c3
Create Date: 2025-09-19 16:09:35.531787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac71f4e22c43'
down_revision: Union[str, Sequence[str], None] = 'aaa252b7c6c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boards', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cards', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('lists', sa.Column('board_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'lists', 'boards', ['board_id'], ['id'])
    op.drop_index(op.f('ix_users_number'), table_name='users')
    op.create_index('uq_users_number', 'users', ['number'], unique=True, mssql_where=sa.text('number IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_users_number', table_name='users', mssql_where=sa.text('number IS NOT NULL'))
    op.create_index(op.f('ix_users_number'), 'users', ['number'], unique=1)
    op.drop_constraint(None, 'lists', type_='foreignkey')
    op.drop_column('lists', 'board_id')
    op.alter_column('cards', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('boards', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
